apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: gedigital
spec:
  selector:
    matchLabels:
      app: nginx
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "8kmilesranjith/nginx:v1"
          stdin: true
          tty: true
          ports:
            - name: http
              containerPort: 80
